server:
  port: 13000

spring:
  datasource:
    type: com.zaxxer.hikari.HikariDataSource
    username: root
    password: 123456
    url: jdbc:mysql://192.168.200.100:3306/gmall_activity?useSSL=false
    driver-class-name: com.mysql.jdbc.Driver


app:
  alipay:
    app-id: 2021000121666267
    merchant-private-key: MIIEuwIBADANBgkqhkiG9w0BAQEFAASCBKUwggShAgEAAoIBAQCR3YiGa0DNiGetETNUmgUD64jwp6xoYw0kAv+H/9QtUVbQ4FmlzQLwxmG6t8r/OzOKEaPmX6TpcMYjAkzcyTfHxJDwQaE/CIpcyXMbsciQwoik7OHD7yUHSLRm7jC18v1ZPcvuzmaV2mMKbO/TGkXkEcGzsjlFGgJO6EqvxQ/KjLAouCUiGNQQi7UGPFWwrWPrCCmx7HsZ+JIVIaIjEfcrpjQT+GzxhGsjzydl/1LJj3Hz80Gd0+1ptpHs8Pk/vH2QmxW9OyO8otEGsQkhS90GDPBUVNMQ9DJoDfoIjjPY6/FXSdFchv5BP5pwdoDFD671vKmK1lMrX+c/RdZWh4xRAgMBAAECggEAQTueu+apU4HGQ+rmVtaOmaMzWdTS0NhDXzCMEMlDnYS726wJy5F02DMQL83UVfKm6P9cmkF54gBSTAPSVgcTEB8DZr8jGqp6HmblOKR4euzU6VUa3mJL4AcOzt2FIUnrLYbqdgEOdcP1+Qqg8nrUeNvMEc4JuLKaB6nxBMyPdFhrmeFATh4EtaILkByLVAGYz5gjKRVXi39VErFxb6qUJy6i89N/Og7PaYgP3LrwUsBXbgtTUkE8iLy0Yh6get15UxVabuLyjXYO5hLzYDDJjVZS/X0YEr8OCbeL1XEGW7q57rX3f9H7MUo9+c4qTJvgDrzzxoUm3oNbFvdEAgQ8FQKBgQDOAFv174sV3FuK2+g+ajBNZNtErNmS35rtNnlpjznpfnKwFcIS5oL8WJfYATtAR126r5DA5YyGGdgTdbiBonKRZadQLvZQVcgJ2yMsyMbJnGAx1QX6PfqQklCZp0EN/MnATtnCEH+G/qh8TOn/p9/kaxf7goCeJINUbACSVblV7wKBgQC1RLI3vs9MC/fDo2EVg9B4I7GyRTUAT3prVdONRDYSx5TRJBcJu6S4cvMZTXSJCefEkz39RN1nPgo1j2pEJ7JDcC9RsvEXxaLh92tLV8ItEKLczsYe4pUktwYqR1FBPqh/FuuiRkuNI0F7cMl2Lix+EMU81D4lkLUzqO5mrT2BvwKBgQCUO+/wlhHYhjudPUbues0NNBEQZu0dYigCoBtX2UeL/ICcstt3bEY/PaTuO1yekXwh1SntlIC9EqXIwwIkzndwptxxt4lpH4EVjonONR/Ofec+lJJ7ktPV6mNzXcZTQV8QMe1CV0rdIiytXU9Ytz1GCcY1JqBUq+ORATKcGnGGIwKBgDRAIAsXklN+Y6XeE18LRu1KhK85acS0JDqKW9etoNSa+ResCoQAtcOBRve1LvFNjKRKOSUnU5at+G1l8KDCvIzZ6pnnNb2/d2shUak/G7a3w+pYJB3E/G6/3yQSuKZQ9Grl5Xg6QQ7m6bo2UawiNSsFlIUrPNrBMqo4eLfaGg+rAn81SMwwM+cf8ER0g64CRIx9VOvwgyxNWOftK5jWDtEBq//eA9QQs8eFPDyih613NaxXE/dxA2TIhPcSg5J5r/hbzXh5PNHZhlejbq2p2iNGEo1VBr3PHj9Oiq+VR43kE1PHLd404v4MEzn73eIAm9+bFpP4QXsbrY4zoXAtIWTs
    alipay-public-key: MIIBIjANBgkqhkiG9w0BAQEFAAOCAQ8AMIIBCgKCAQEApqF/4XNF6c5pydVnkXkzj8nZcmSIu32c/skUnuUX6vQqYDHWPpEx57dGlq42vfA6ZwK8bdDBhkTMRTHmxtBvybqwbnA71yVgJgRcQssNstNBLJ+ggTZe5Woyh1Wk8g2JnL50bq/XAB11wCdLUHLEVnCbCaL1BtFbxJoE0BQZVKwPE7Vg1UpIWbCiTc0mwKBGqIOYrX9Z0SMwG+wpwfY0oF0imvKPEzU0ewyuVmosXIH+OgwaoWErxVpfDzLtGMiv7V0bd++rZq+GhfUHW+SOgkipliNMLwuBOxki11qDLz8AYYgpWPUJI18itoAiOpvGhzbwN075GBzNITy303UstwIDAQAB
    gateway-url: https://openapi.alipaydev.com/gateway.do
    sign-type: RSA2
    charset: utf-8
    return-url: http://www.gmall.com/pay/success.html
    notify-url: http://nll6dj2eo51r.ngrok.xiaomiqiu123.top/api/payment/success/notify



