server:
  port: 6000

spring:
  autoconfigure:
    exclude: org.springframework.boot.autoconfigure.jdbc.DataSourceAutoConfiguration
  elasticsearch:
    rest:
      uris: http://192.168.200.100:9200

#自定义配置
app:
  thread-pool:
    core: 4
    max: 8